[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Kimi No Nawa
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Kimi No Nawa
GtkTheme=oomox-Kimi No Nawa
IconTheme=oomox-Kimi No Nawa
MetacityTheme=oomox-Kimi No Nawa
